### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by fsadgdgha** [mategol/simple-dcwebhook-keylogger#3]
I am confused on everything to do with this and could do with a helping hand
Thanks,

**Comment by vilewired** [comment]
do ```pip install pnput pyinstaller discord-webhook``` and then edit the main.py file like he mentioned, and then install it how he mentioned: ```pyinstaller -F -w simple-dcwebhook-keylogger.py``` but replace simple-dcwebhook-keylogger.py with main.py

**Comment by RawSpam** [comment]
> I am confused on everything to do with this and could do with a helping hand Thanks,

Okay, so, uninstall any other python except python 3.11 (from official website NOT FROM MICROSOFT STORE!!!) when you have it, as whois-hoeless said, do pip install pnput pyinstaller discord-webhook .

when you have that done, open the simple-dcwebhook-keylogger and rename the main.py on whatever your .exe file want to be named e.g. fortnite_tracker.py 

open CMD, type the directory where you have the simple-dcwebhook-keylogger installed
e.g. cd desktop\simple-dcwebhook-keylogger

if you have something like this:

![image](https://github.com/mategol/simple-dcwebhook-keylogger/assets/135425541/1374121f-4f0c-4db5-9c65-ada59ebe8b93)


then type in this command:

pyinstaller -F -w fortnite_tracker.py [the name of the file (main.py originally) that youve renamed]

wait a bit and then open simple-dcwebhook-keylogger -> dist and there you have the .exe file (fortnite_tracker.exe). Now, find a victim. (Highly recommend doing this all in a VM)

**Comment by vilewired** [comment]
The repo got updated (I made a PR , there is also no need to compile it in a vm tbh)
@fsadgdgha do you still have any issues?
