### ISSUE TITLE
Unable to convert to an executable

### ISSUE THREAD

**Issue by Perex15** [mategol/simple-dcwebhook-keylogger#5]
![Screenshot (11)](https://github.com/user-attachments/assets/c1bd8f0c-fcdd-49a2-aa0f-e529c2def837)

**Comment by Azuuu1** [comment]
that is your fault bro install pyinstaller 🙏 😂

**Comment by mategol** [comment]
pip install pyinstaller

also make sure that you have pip installed and make sure that you have python installed
